apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app
  namespace: argocd
spec:
  destination:
    namespace: gitops-kubernetes
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/AdamDubnytskyy/gitops-k8s-playground.git
    path: deployment
    targetRevision: main