apiVersion: apps/v1
kind: Deployment
metadata:
  name: lviv-weather-app
  labels:
    app: lviv-weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lviv-weather-app
  template:
    metadata:
      labels:
        app: lviv-weather-app
    spec:
      containers:
      - name: lviv-weather-app
        image: pietrolibro/zurich-weather-app:1.0
        ports:
        - containerPort: 8080
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
