name: Create Docker Image CI
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag broox/hello-world-py-app:${GITHUB_SHA}
